import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface QnAItem {
    question: string;
    userAnswer: string;
    feedback?: {
        grammarFix: string;
        betterAnswer: string;
        score: number;
    };
}

export const generatePDF = (role: string, qnaHistory: QnAItem[], avgScore: number) => {
    const doc = new jsPDF();

    // 1. HEADER
    doc.setFillColor(10, 10, 10); // Dark Background
    doc.rect(0, 0, 210, 40, "F"); // Header Box

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Interview Analysis Report", 14, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    doc.text(`Role: ${role} | Date: ${new Date().toLocaleDateString()}`, 14, 30);

    // 2. SCORE SUMMARY
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Performance Summary", 14, 50);

    autoTable(doc, {
        startY: 55,
        head: [["Metric", "Value"]],
        body: [
            ["Overall Score", `${avgScore}/100`],
            ["Questions Answered", `${qnaHistory.length}`],
            ["Result Status", avgScore > 70 ? "PASSED" : "NEEDS IMPROVEMENT"],
        ],
        theme: "grid",
        headStyles: { fillColor: [79, 70, 229] }, // Indigo color
        styles: { fontSize: 12 },
    });

    // 3. DETAILED BREAKDOWN
    // We use (doc as any) to access the autoTable property which TS sometimes misses
    let finalY = (doc as any).lastAutoTable.finalY + 15;

    doc.setFontSize(14);
    doc.text("Detailed Question Analysis", 14, finalY);

    qnaHistory.forEach((item, index) => {
        // Add page break if needed
        if (finalY > 250) {
            doc.addPage();
            finalY = 20;
        }

        autoTable(doc, {
            startY: finalY + 5,
            head: [[`Q${index + 1}: ${item.question}`]],
            body: [
                ["YOUR ANSWER:"],
                [item.userAnswer],
                [""], // Spacer
                ["AI FEEDBACK & IMPROVEMENT:"],
                [item.feedback?.betterAnswer || "No feedback generated."]
            ],
            theme: "plain",
            headStyles: { fillColor: [50, 50, 50], textColor: 255, fontSize: 11 },
            bodyStyles: { fontSize: 10, cellPadding: 4 },
            columnStyles: {
                0: { cellWidth: 180 } // Force full width
            },
            didParseCell: (data) => {
                // Style specific rows
                if (data.row.index === 0 || data.row.index === 3) {
                    data.cell.styles.fontStyle = 'bold';
                    data.cell.styles.textColor = [79, 70, 229]; // Indigo
                }
            }
        });

        finalY = (doc as any).lastAutoTable.finalY + 10;
    });

    // 4. FOOTER
    // FIX: Cast to any to bypass the missing type definition
    const pageCount = (doc as any).internal.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by AI Interviewer - Page ${i} of ${pageCount}`, 105, 290, { align: "center" });
    }

    // 5. SAVE
    doc.save(`Interview_Report_${role.replace(/\s+/g, "_")}.pdf`);
};